language: node_js
node_js:
  - lts/*
  - node
 os:
  - linux
  - osx
before_install:
  - |-
    if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
     then
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc;
      else
        echo "//registry.npmjs.org/:_authToken=\${NPM_INSTALL_TOKEN}" > ~/.npmrc;
    fi
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
  - npm install -g codecov
install:
  - npm i -g @labshare/lsc codecov
  - npm i
  - npm run build
script:
  - npm run lint
  - npm run coverage
after_success:
  - codecov
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  allow_failures:
    - node_js: node
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release