language: node_js
node_js:
  - lts/*
  - node
before_install:
  - git config --global url."git@github.com:".insteadOf "https://github.com/"
script:
  - npm test
  - >-
    npm run coverage && cat ./coverage/lcov.info |
    ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
cache:
  directories:
    - ~/.npm
notifications:
  email: false
after_success:
  - npm run semantic-release
branches:
  except:
    - /^vd+.d+.d+$/
