language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - lts/*
  - node
before_install:
  - |-
    if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
     then
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc;
      else
        echo "//registry.npmjs.org/:_authToken=\${NPM_INSTALL_TOKEN}" > ~/.npmrc;
    fi
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
  
install:
  - npm install -g codecov
  - npm install
  - npm run build
script:
  - npm test
  - >-
    npm run coverage && cat ./coverage/lcov.info |
    ./node_modules/coveralls/bin/coveralls.js
  - codecov
cache:
  directories:
    - ~/.npm
notifications:
  email: false
branches:
  except:
    - /^vd+.d+.d+$/
jobs:
  allow_failures:
    - node_js: node
  include:
    - stage: release
      if: branch = master
      language: node_js
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
